{% set name = "environments_utils" %}
{% set version = "1.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/environments_utils-{{ version }}.tar.gz
  sha256: 85126a7be4e2ee4e604f4a44abe46bb0fd520726cf9d1cd70afcf04191d7af92

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - environments_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LucaCappelletti94/environments_utils
  summary: Utilities to identify which environments is your python script running within.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - dillonroach
